### ISSUE TITLE
Logger from astropy?

### ISSUE THREAD

**Issue by j-faria** [Kamuish/serval#13]
```python
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    builder()
  File "/home/joao/Software/serval/src/serval.py", line 2258, in builder
    sys.exit(serval())
  File "/home/joao/Software/serval/src/serval.py", line 981, in serval
    sp = Spectrum(filename, inst=inst, pfits=2 if 'HARPS' in inst.name else True, drs=drs, fib=fib, targ=targ, verb=True)
  File "/home/joao/Software/serval/src/read_spec.py", line 168, in __init__
    (_, self.bjd, _), (self.berv_start, self.berv, self.berv_end) = brv_we14py.bjdbrv(jd_utc=jd_utcs, ra=ra, dec=de, obsname=obsname, pmra=targ.pmra, pmdec=targ.pmde, parallax=0., rv=0., zmeas=[0], **obsloc)
  File "/home/joao/Software/serval/src/brv_we14py.py", line 77, in bjdbrv
    pmdec=pmdec, px=parallax, lat=lat, longi=lon, alt=elevation, **kwargs)
  File "/home/joao/anaconda3/lib/python3.7/site-packages/barycorrpy/barycorrpy.py", line 205, in get_BC_vel
    ephemeris=ephemeris, leap_dir=leap_dir, leap_update=leap_update, predictive=predictive, **star_output)
  File "/home/joao/anaconda3/lib/python3.7/site-packages/barycorrpy/barycorrpy.py", line 266, in BCPy
    earth_geo = get_body_barycentric_posvel('earth', JDTDB, ephemeris=ephemeris) # [km]
  File "/home/joao/anaconda3/lib/python3.7/site-packages/astropy/coordinates/solar_system.py", line 330, in get_body_barycentric_posvel
    return _get_body_barycentric_posvel(body, time, ephemeris)
  File "/home/joao/anaconda3/lib/python3.7/site-packages/astropy/coordinates/solar_system.py", line 213, in _get_body_barycentric_posvel
    kernel = _get_kernel(ephemeris)
  File "/home/joao/anaconda3/lib/python3.7/site-packages/astropy/coordinates/solar_system.py", line 172, in _get_kernel
    return SPK.open(download_file(value, cache=True))
  File "/home/joao/anaconda3/lib/python3.7/site-packages/astropy/utils/data.py", line 1042, in download_file
    if show_progress and sys.stdout.isatty():
AttributeError: 'Logger' object has no attribute 'isatty'
```

**Comment by Kamuish** [comment]
Isso apareceu-me uma vez, mas quando voltei a correr não apareceu mais. Presumo que seja um erro interno ao astropy. 

Vou ver se consigo reproduzir

**Comment by Kamuish** [comment]
Found it. o sys.stdout é overriden pela class de Logging. 

É estranho apenas aparecer de vez em quando e não sempre .... Vou dar fix daqui a um bocado. Quando estiver feito eu fecho este issue

**Comment by Kamuish** [comment]
@j-faria já dei disable do override do sys-stdout. Quando conseguires testa, para ver se também não te aparece nada, e para fechar o issue

Lembro-me de seguir este erro até uma interface de download de algum tipo de ficheiros. Se o erro apareceu depois do download (e assumindo que esse ficheiro seja guardado localmente depois do download), presumo que só volte a aparecer noutros casos
